apiVersion: v1  
kind: Service
metadata:
  name: authmongo-svc
spec:
  clusterIP: None
  selector:
    role: authmongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "authmongo-svc"
  replicas: 1
  selector:
    matchLabels:
      role: authmongo
  template:
    metadata:
      labels:
        role: authmongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:latest
          ports:
          - containerPort: 27017
          resources:
            limits:
              memory: 800Mi
              cpu: 500m
            requests:
              memory: 700Mi
              cpu: 500m
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: password
          volumeMounts:
            - name: mongo-auth-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-auth-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi