apiVersion: v1
kind: Secret
metadata:
  name: my-auth
  namespace: app
type: Opaque
data:
  ADDRESS_AUTH: OjkwOTA=
  RABBITMQ_ADD: YW1xcDovL3VzZXI6bXlwYXNzd29yZEByYWJiaXRtcS0wLnJhYmJpdC1zdmMuZGIuc3ZjLmNsdXN0ZXIubG9jYWw6NTY3Mi8=
  SECRET_KEY: c2VjcmV0
  MONGODB_URL: bW9uZ29kYjovL3VzZXI6cGFzc3dvcmRAbW9uZ28tMC5hdXRobW9uZ28tc3ZjLmRiLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3Lw==